language: node_js

sudo: false

cache: yarn

node_js:
  - "8"
  - "6"
  - "4"

before_install:
  - "npm install -g yarn"

install:
  - yarn

script:
  - gulp build typescript:test

after_success:
  - bash <(curl -s https://codecov.io/bash)
